Search.appendIndex(
    [
                {
            "fqsen": "\\SajedZarinpour\\Spotplayer\\Controllers\\SpotPlayerController",
            "name": "SpotPlayerController",
            "summary": "",
            "url": "classes/SajedZarinpour-Spotplayer-Controllers-SpotPlayerController.html"
        },                {
            "fqsen": "\\SajedZarinpour\\Spotplayer\\Controllers\\SpotPlayerController\u003A\u003AgenerateCookie\u0028\u0029",
            "name": "generateCookie",
            "summary": "Generate\u0020cookie\u0020X\u0020for\u0020spot\u0020player.",
            "url": "classes/SajedZarinpour-Spotplayer-Controllers-SpotPlayerController.html#method_generateCookie"
        },                {
            "fqsen": "\\SajedZarinpour\\Spotplayer\\Facades\\SpotPlayer",
            "name": "SpotPlayer",
            "summary": "",
            "url": "classes/SajedZarinpour-Spotplayer-Facades-SpotPlayer.html"
        },                {
            "fqsen": "\\SajedZarinpour\\Spotplayer\\Facades\\SpotPlayer\u003A\u003AgetFacadeAccessor\u0028\u0029",
            "name": "getFacadeAccessor",
            "summary": "Declaring\u0020the\u0020accessor\u0020for\u0020this\u0020Facade.",
            "url": "classes/SajedZarinpour-Spotplayer-Facades-SpotPlayer.html#method_getFacadeAccessor"
        },                {
            "fqsen": "\\spotplayer\u0028\u0029",
            "name": "spotplayer",
            "summary": "",
            "url": "namespaces/default.html#function_spotplayer"
        },                {
            "fqsen": "\\SajedZarinpour\\Spotplayer\\Providers\\SpotPlayerServiceProvider",
            "name": "SpotPlayerServiceProvider",
            "summary": "",
            "url": "classes/SajedZarinpour-Spotplayer-Providers-SpotPlayerServiceProvider.html"
        },                {
            "fqsen": "\\SajedZarinpour\\Spotplayer\\Providers\\SpotPlayerServiceProvider\u003A\u003Aregister\u0028\u0029",
            "name": "register",
            "summary": "Register\u0020services.",
            "url": "classes/SajedZarinpour-Spotplayer-Providers-SpotPlayerServiceProvider.html#method_register"
        },                {
            "fqsen": "\\SajedZarinpour\\Spotplayer\\Providers\\SpotPlayerServiceProvider\u003A\u003Aboot\u0028\u0029",
            "name": "boot",
            "summary": "Bootstrap\u0020services.",
            "url": "classes/SajedZarinpour-Spotplayer-Providers-SpotPlayerServiceProvider.html#method_boot"
        },                {
            "fqsen": "\\SajedZarinpour\\Spotplayer\\SpotPlayer",
            "name": "SpotPlayer",
            "summary": "",
            "url": "classes/SajedZarinpour-Spotplayer-SpotPlayer.html"
        },                {
            "fqsen": "\\SajedZarinpour\\Spotplayer\\SpotPlayer\u003A\u003AcheckCookie\u0028\u0029",
            "name": "checkCookie",
            "summary": "Check\u0020if\u0020the\u0020cookie\u0020is\u0020still\u0020valid.",
            "url": "classes/SajedZarinpour-Spotplayer-SpotPlayer.html#method_checkCookie"
        },                {
            "fqsen": "\\SajedZarinpour\\Spotplayer\\SpotPlayer\u003A\u003AgenerateCookie\u0028\u0029",
            "name": "generateCookie",
            "summary": "Generating\u0020cookie.",
            "url": "classes/SajedZarinpour-Spotplayer-SpotPlayer.html#method_generateCookie"
        },                {
            "fqsen": "\\SajedZarinpour\\Spotplayer\\SpotPlayer\u003A\u003Afilter\u0028\u0029",
            "name": "filter",
            "summary": "Ommit\u0020all\u0020null\u0020values\u0020from\u0020the\u0020options\u0020array.",
            "url": "classes/SajedZarinpour-Spotplayer-SpotPlayer.html#method_filter"
        },                {
            "fqsen": "\\SajedZarinpour\\Spotplayer\\SpotPlayer\u003A\u003Arequest\u0028\u0029",
            "name": "request",
            "summary": "Setting\u0020up\u0020request\u0020to\u0020send\u0020to\u0020api\u0020end\u0020point.",
            "url": "classes/SajedZarinpour-Spotplayer-SpotPlayer.html#method_request"
        },                {
            "fqsen": "\\SajedZarinpour\\Spotplayer\\SpotPlayer\u003A\u003AgetJSONFileList\u0028\u0029",
            "name": "getJSONFileList",
            "summary": "Get\u0020files\u0020as\u0020JSON.",
            "url": "classes/SajedZarinpour-Spotplayer-SpotPlayer.html#method_getJSONFileList"
        },                {
            "fqsen": "\\SajedZarinpour\\Spotplayer\\SpotPlayer\u003A\u003AgetAllLicences\u0028\u0029",
            "name": "getAllLicences",
            "summary": "Get\u0020all\u0020licenses.",
            "url": "classes/SajedZarinpour-Spotplayer-SpotPlayer.html#method_getAllLicences"
        },                {
            "fqsen": "\\SajedZarinpour\\Spotplayer\\SpotPlayer\u003A\u003AgetAllCourses\u0028\u0029",
            "name": "getAllCourses",
            "summary": "Get\u0020All\u0020the\u0020courses\u0020for\u0020a\u0020license.",
            "url": "classes/SajedZarinpour-Spotplayer-SpotPlayer.html#method_getAllCourses"
        },                {
            "fqsen": "\\SajedZarinpour\\Spotplayer\\SpotPlayer\u003A\u003AgetCourseDetail\u0028\u0029",
            "name": "getCourseDetail",
            "summary": "Get\u0020the\u0020detail\u0020for\u0020one\u0020course.",
            "url": "classes/SajedZarinpour-Spotplayer-SpotPlayer.html#method_getCourseDetail"
        },                {
            "fqsen": "\\SajedZarinpour\\Spotplayer\\SpotPlayer\u003A\u003AsetDevice\u0028\u0029",
            "name": "setDevice",
            "summary": "To\u0020set\u0020up\u0020the\u0020\u0024device\u0020array\u0020in\u0020a\u0020convinient\u0020way.",
            "url": "classes/SajedZarinpour-Spotplayer-SpotPlayer.html#method_setDevice"
        },                {
            "fqsen": "\\SajedZarinpour\\Spotplayer\\SpotPlayer\u003A\u003Alicence\u0028\u0029",
            "name": "licence",
            "summary": "generate\u0020a\u0020spotplayer\u0020licence\u0020for\u0020the\u0020given\u0020values.",
            "url": "classes/SajedZarinpour-Spotplayer-SpotPlayer.html#method_licence"
        },                {
            "fqsen": "\\SajedZarinpour\\Spotplayer\\SpotPlayer\u003A\u003AgetLicenseData\u0028\u0029",
            "name": "getLicenseData",
            "summary": "Get\u0020a\u0020licence\u0020description.",
            "url": "classes/SajedZarinpour-Spotplayer-SpotPlayer.html#method_getLicenseData"
        },                {
            "fqsen": "\\SajedZarinpour\\Spotplayer\\SpotPlayer\u003A\u003AupdateLicense\u0028\u0029",
            "name": "updateLicense",
            "summary": "Update\u0020a\u0020spotplayer\u0020licence\u0020for\u0020the\u0020given\u0020values.",
            "url": "classes/SajedZarinpour-Spotplayer-SpotPlayer.html#method_updateLicense"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\SajedZarinpour\\Spotplayer\\Controllers",
            "name": "Controllers",
            "summary": "",
            "url": "namespaces/sajedzarinpour-spotplayer-controllers.html"
        },                {
            "fqsen": "\\SajedZarinpour\\Spotplayer\\Facades",
            "name": "Facades",
            "summary": "",
            "url": "namespaces/sajedzarinpour-spotplayer-facades.html"
        },                {
            "fqsen": "\\SajedZarinpour\\Spotplayer\\Providers",
            "name": "Providers",
            "summary": "",
            "url": "namespaces/sajedzarinpour-spotplayer-providers.html"
        },                {
            "fqsen": "\\SajedZarinpour\\Spotplayer",
            "name": "Spotplayer",
            "summary": "",
            "url": "namespaces/sajedzarinpour-spotplayer.html"
        },                {
            "fqsen": "\\SajedZarinpour",
            "name": "SajedZarinpour",
            "summary": "",
            "url": "namespaces/sajedzarinpour.html"
        }            ]
);
