Search.appendIndex(
    [
                {
            "fqsen": "\\SajedZarinpour\\Spotplayer\\Controllers\\SpotPlayerController",
            "name": "SpotPlayerController",
            "summary": "",
            "url": "classes/SajedZarinpour-Spotplayer-Controllers-SpotPlayerController.html"
        },                {
            "fqsen": "\\SajedZarinpour\\Spotplayer\\Controllers\\SpotPlayerController\u003A\u003AgenerateCookie\u0028\u0029",
            "name": "generateCookie",
            "summary": "Generate\u0020cookie\u0020X\u0020for\u0020spot\u0020player.",
            "url": "classes/SajedZarinpour-Spotplayer-Controllers-SpotPlayerController.html#method_generateCookie"
        },                {
            "fqsen": "\\SajedZarinpour\\Spotplayer\\Facades\\SpotPlayer",
            "name": "SpotPlayer",
            "summary": "",
            "url": "classes/SajedZarinpour-Spotplayer-Facades-SpotPlayer.html"
        },                {
            "fqsen": "\\SajedZarinpour\\Spotplayer\\Facades\\SpotPlayer\u003A\u003AgetFacadeAccessor\u0028\u0029",
            "name": "getFacadeAccessor",
            "summary": "Declaring\u0020the\u0020accessor\u0020for\u0020this\u0020Facade.",
            "url": "classes/SajedZarinpour-Spotplayer-Facades-SpotPlayer.html#method_getFacadeAccessor"
        },                {
            "fqsen": "\\spotplayer\u0028\u0029",
            "name": "spotplayer",
            "summary": "",
            "url": "namespaces/default.html#function_spotplayer"
        },                {
            "fqsen": "\\SajedZarinpour\\Spotplayer\\Models\\Course",
            "name": "Course",
            "summary": "",
            "url": "classes/SajedZarinpour-Spotplayer-Models-Course.html"
        },                {
            "fqsen": "\\SajedZarinpour\\Spotplayer\\Models\\Course\u003A\u003Alicences\u0028\u0029",
            "name": "licences",
            "summary": "The\u0020licences\u0020that\u0020belong\u0020to\u0020the\u0020course.",
            "url": "classes/SajedZarinpour-Spotplayer-Models-Course.html#method_licences"
        },                {
            "fqsen": "\\SajedZarinpour\\Spotplayer\\Models\\Course\u003A\u003A\u0024table",
            "name": "table",
            "summary": "The\u0020table\u0020associated\u0020with\u0020the\u0020model.",
            "url": "classes/SajedZarinpour-Spotplayer-Models-Course.html#property_table"
        },                {
            "fqsen": "\\SajedZarinpour\\Spotplayer\\Models\\CourseLicence",
            "name": "CourseLicence",
            "summary": "",
            "url": "classes/SajedZarinpour-Spotplayer-Models-CourseLicence.html"
        },                {
            "fqsen": "\\SajedZarinpour\\Spotplayer\\Models\\CourseLicence\u003A\u003A\u0024table",
            "name": "table",
            "summary": "The\u0020table\u0020associated\u0020with\u0020the\u0020model.",
            "url": "classes/SajedZarinpour-Spotplayer-Models-CourseLicence.html#property_table"
        },                {
            "fqsen": "\\SajedZarinpour\\Spotplayer\\Models\\Licence",
            "name": "Licence",
            "summary": "",
            "url": "classes/SajedZarinpour-Spotplayer-Models-Licence.html"
        },                {
            "fqsen": "\\SajedZarinpour\\Spotplayer\\Models\\Licence\u003A\u003Acourses\u0028\u0029",
            "name": "courses",
            "summary": "The\u0020courses\u0020that\u0020belong\u0020to\u0020the\u0020licence.",
            "url": "classes/SajedZarinpour-Spotplayer-Models-Licence.html#method_courses"
        },                {
            "fqsen": "\\SajedZarinpour\\Spotplayer\\Models\\Licence\u003A\u003A\u0024table",
            "name": "table",
            "summary": "The\u0020table\u0020associated\u0020with\u0020the\u0020model.",
            "url": "classes/SajedZarinpour-Spotplayer-Models-Licence.html#property_table"
        },                {
            "fqsen": "\\SajedZarinpour\\Spotplayer\\Providers\\SpotPlayerServiceProvider",
            "name": "SpotPlayerServiceProvider",
            "summary": "",
            "url": "classes/SajedZarinpour-Spotplayer-Providers-SpotPlayerServiceProvider.html"
        },                {
            "fqsen": "\\SajedZarinpour\\Spotplayer\\Providers\\SpotPlayerServiceProvider\u003A\u003Aregister\u0028\u0029",
            "name": "register",
            "summary": "Register\u0020services.",
            "url": "classes/SajedZarinpour-Spotplayer-Providers-SpotPlayerServiceProvider.html#method_register"
        },                {
            "fqsen": "\\SajedZarinpour\\Spotplayer\\Providers\\SpotPlayerServiceProvider\u003A\u003Aboot\u0028\u0029",
            "name": "boot",
            "summary": "Bootstrap\u0020services.",
            "url": "classes/SajedZarinpour-Spotplayer-Providers-SpotPlayerServiceProvider.html#method_boot"
        },                {
            "fqsen": "\\SajedZarinpour\\Spotplayer\\SpotPlayer",
            "name": "SpotPlayer",
            "summary": "",
            "url": "classes/SajedZarinpour-Spotplayer-SpotPlayer.html"
        },                {
            "fqsen": "\\SajedZarinpour\\Spotplayer\\SpotPlayer\u003A\u003AcheckCookie\u0028\u0029",
            "name": "checkCookie",
            "summary": "Check\u0020if\u0020the\u0020cookie\u0020is\u0020still\u0020valid.",
            "url": "classes/SajedZarinpour-Spotplayer-SpotPlayer.html#method_checkCookie"
        },                {
            "fqsen": "\\SajedZarinpour\\Spotplayer\\SpotPlayer\u003A\u003AgenerateCookie\u0028\u0029",
            "name": "generateCookie",
            "summary": "Generating\u0020cookie.",
            "url": "classes/SajedZarinpour-Spotplayer-SpotPlayer.html#method_generateCookie"
        },                {
            "fqsen": "\\SajedZarinpour\\Spotplayer\\SpotPlayer\u003A\u003Afilter\u0028\u0029",
            "name": "filter",
            "summary": "Ommit\u0020all\u0020null\u0020values\u0020from\u0020the\u0020options\u0020array.",
            "url": "classes/SajedZarinpour-Spotplayer-SpotPlayer.html#method_filter"
        },                {
            "fqsen": "\\SajedZarinpour\\Spotplayer\\SpotPlayer\u003A\u003Arequest\u0028\u0029",
            "name": "request",
            "summary": "Setting\u0020up\u0020request\u0020to\u0020send\u0020to\u0020api\u0020end\u0020point.",
            "url": "classes/SajedZarinpour-Spotplayer-SpotPlayer.html#method_request"
        },                {
            "fqsen": "\\SajedZarinpour\\Spotplayer\\SpotPlayer\u003A\u003AgetJSONFileList\u0028\u0029",
            "name": "getJSONFileList",
            "summary": "Get\u0020files\u0020as\u0020JSON.",
            "url": "classes/SajedZarinpour-Spotplayer-SpotPlayer.html#method_getJSONFileList"
        },                {
            "fqsen": "\\SajedZarinpour\\Spotplayer\\SpotPlayer\u003A\u003AgetAllLicences\u0028\u0029",
            "name": "getAllLicences",
            "summary": "Get\u0020all\u0020licenses.",
            "url": "classes/SajedZarinpour-Spotplayer-SpotPlayer.html#method_getAllLicences"
        },                {
            "fqsen": "\\SajedZarinpour\\Spotplayer\\SpotPlayer\u003A\u003AgetAllCourses\u0028\u0029",
            "name": "getAllCourses",
            "summary": "Get\u0020All\u0020the\u0020courses\u0020for\u0020a\u0020license.",
            "url": "classes/SajedZarinpour-Spotplayer-SpotPlayer.html#method_getAllCourses"
        },                {
            "fqsen": "\\SajedZarinpour\\Spotplayer\\SpotPlayer\u003A\u003AgetCourseDetail\u0028\u0029",
            "name": "getCourseDetail",
            "summary": "Get\u0020the\u0020detail\u0020for\u0020one\u0020course.",
            "url": "classes/SajedZarinpour-Spotplayer-SpotPlayer.html#method_getCourseDetail"
        },                {
            "fqsen": "\\SajedZarinpour\\Spotplayer\\SpotPlayer\u003A\u003AsetDevice\u0028\u0029",
            "name": "setDevice",
            "summary": "To\u0020set\u0020up\u0020the\u0020\u0024device\u0020array\u0020in\u0020a\u0020convinient\u0020way.",
            "url": "classes/SajedZarinpour-Spotplayer-SpotPlayer.html#method_setDevice"
        },                {
            "fqsen": "\\SajedZarinpour\\Spotplayer\\SpotPlayer\u003A\u003Alicence\u0028\u0029",
            "name": "licence",
            "summary": "generate\u0020a\u0020spotplayer\u0020licence\u0020for\u0020the\u0020given\u0020values.",
            "url": "classes/SajedZarinpour-Spotplayer-SpotPlayer.html#method_licence"
        },                {
            "fqsen": "\\SajedZarinpour\\Spotplayer\\SpotPlayer\u003A\u003AgetLicenseData\u0028\u0029",
            "name": "getLicenseData",
            "summary": "Get\u0020a\u0020licence\u0020description.",
            "url": "classes/SajedZarinpour-Spotplayer-SpotPlayer.html#method_getLicenseData"
        },                {
            "fqsen": "\\SajedZarinpour\\Spotplayer\\SpotPlayer\u003A\u003AupdateLicense\u0028\u0029",
            "name": "updateLicense",
            "summary": "Update\u0020a\u0020spotplayer\u0020licence\u0020for\u0020the\u0020given\u0020values.",
            "url": "classes/SajedZarinpour-Spotplayer-SpotPlayer.html#method_updateLicense"
        },                {
            "fqsen": "\\SajedZarinpour\\Spotplayer\\Traits\\UserOwnedSpotPlayerLicence",
            "name": "UserOwnedSpotPlayerLicence",
            "summary": "",
            "url": "classes/SajedZarinpour-Spotplayer-Traits-UserOwnedSpotPlayerLicence.html"
        },                {
            "fqsen": "\\SajedZarinpour\\Spotplayer\\Traits\\UserOwnedSpotPlayerLicence\u003A\u003Alicences\u0028\u0029",
            "name": "licences",
            "summary": "Get\u0020the\u0020licences\u0020for\u0020the\u0020user.",
            "url": "classes/SajedZarinpour-Spotplayer-Traits-UserOwnedSpotPlayerLicence.html#method_licences"
        },                {
            "fqsen": "\\SajedZarinpour\\Spotplayer\\Traits\\UserOwnedSpotPlayerLicence\u003A\u003ApublishedCourses\u0028\u0029",
            "name": "publishedCourses",
            "summary": "Get\u0020the\u0020published\u0020courses\u0020of\u0020the\u0020user.",
            "url": "classes/SajedZarinpour-Spotplayer-Traits-UserOwnedSpotPlayerLicence.html#method_publishedCourses"
        },                {
            "fqsen": "\\SajedZarinpour\\Spotplayer\\Traits\\UserOwnedSpotPlayerLicence\u003A\u003Asubscribedcourses\u0028\u0029",
            "name": "subscribedcourses",
            "summary": "Get\u0020the\u0020subscribed\u0020courses\u0020for\u0020the\u0020user.",
            "url": "classes/SajedZarinpour-Spotplayer-Traits-UserOwnedSpotPlayerLicence.html#method_subscribedcourses"
        },                {
            "fqsen": "\\ComposerAutoloaderInitfdfb8631f88fa5bdf53865160d564205",
            "name": "ComposerAutoloaderInitfdfb8631f88fa5bdf53865160d564205",
            "summary": "",
            "url": "classes/ComposerAutoloaderInitfdfb8631f88fa5bdf53865160d564205.html"
        },                {
            "fqsen": "\\ComposerAutoloaderInitfdfb8631f88fa5bdf53865160d564205\u003A\u003AloadClassLoader\u0028\u0029",
            "name": "loadClassLoader",
            "summary": "",
            "url": "classes/ComposerAutoloaderInitfdfb8631f88fa5bdf53865160d564205.html#method_loadClassLoader"
        },                {
            "fqsen": "\\ComposerAutoloaderInitfdfb8631f88fa5bdf53865160d564205\u003A\u003AgetLoader\u0028\u0029",
            "name": "getLoader",
            "summary": "",
            "url": "classes/ComposerAutoloaderInitfdfb8631f88fa5bdf53865160d564205.html#method_getLoader"
        },                {
            "fqsen": "\\ComposerAutoloaderInitfdfb8631f88fa5bdf53865160d564205\u003A\u003A\u0024loader",
            "name": "loader",
            "summary": "",
            "url": "classes/ComposerAutoloaderInitfdfb8631f88fa5bdf53865160d564205.html#property_loader"
        },                {
            "fqsen": "\\Composer\\Autoload\\ComposerStaticInitfdfb8631f88fa5bdf53865160d564205",
            "name": "ComposerStaticInitfdfb8631f88fa5bdf53865160d564205",
            "summary": "",
            "url": "classes/Composer-Autoload-ComposerStaticInitfdfb8631f88fa5bdf53865160d564205.html"
        },                {
            "fqsen": "\\Composer\\Autoload\\ComposerStaticInitfdfb8631f88fa5bdf53865160d564205\u003A\u003AgetInitializer\u0028\u0029",
            "name": "getInitializer",
            "summary": "",
            "url": "classes/Composer-Autoload-ComposerStaticInitfdfb8631f88fa5bdf53865160d564205.html#method_getInitializer"
        },                {
            "fqsen": "\\Composer\\Autoload\\ComposerStaticInitfdfb8631f88fa5bdf53865160d564205\u003A\u003A\u0024prefixLengthsPsr4",
            "name": "prefixLengthsPsr4",
            "summary": "",
            "url": "classes/Composer-Autoload-ComposerStaticInitfdfb8631f88fa5bdf53865160d564205.html#property_prefixLengthsPsr4"
        },                {
            "fqsen": "\\Composer\\Autoload\\ComposerStaticInitfdfb8631f88fa5bdf53865160d564205\u003A\u003A\u0024prefixDirsPsr4",
            "name": "prefixDirsPsr4",
            "summary": "",
            "url": "classes/Composer-Autoload-ComposerStaticInitfdfb8631f88fa5bdf53865160d564205.html#property_prefixDirsPsr4"
        },                {
            "fqsen": "\\Composer\\Autoload\\ComposerStaticInitfdfb8631f88fa5bdf53865160d564205\u003A\u003A\u0024classMap",
            "name": "classMap",
            "summary": "",
            "url": "classes/Composer-Autoload-ComposerStaticInitfdfb8631f88fa5bdf53865160d564205.html#property_classMap"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader",
            "name": "ClassLoader",
            "summary": "ClassLoader\u0020implements\u0020a\u0020PSR\u002D0,\u0020PSR\u002D4\u0020and\u0020classmap\u0020class\u0020loader.",
            "url": "classes/Composer-Autoload-ClassLoader.html"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Composer-Autoload-ClassLoader.html#method___construct"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader\u003A\u003AgetPrefixes\u0028\u0029",
            "name": "getPrefixes",
            "summary": "",
            "url": "classes/Composer-Autoload-ClassLoader.html#method_getPrefixes"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader\u003A\u003AgetPrefixesPsr4\u0028\u0029",
            "name": "getPrefixesPsr4",
            "summary": "",
            "url": "classes/Composer-Autoload-ClassLoader.html#method_getPrefixesPsr4"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader\u003A\u003AgetFallbackDirs\u0028\u0029",
            "name": "getFallbackDirs",
            "summary": "",
            "url": "classes/Composer-Autoload-ClassLoader.html#method_getFallbackDirs"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader\u003A\u003AgetFallbackDirsPsr4\u0028\u0029",
            "name": "getFallbackDirsPsr4",
            "summary": "",
            "url": "classes/Composer-Autoload-ClassLoader.html#method_getFallbackDirsPsr4"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader\u003A\u003AgetClassMap\u0028\u0029",
            "name": "getClassMap",
            "summary": "",
            "url": "classes/Composer-Autoload-ClassLoader.html#method_getClassMap"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader\u003A\u003AaddClassMap\u0028\u0029",
            "name": "addClassMap",
            "summary": "",
            "url": "classes/Composer-Autoload-ClassLoader.html#method_addClassMap"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader\u003A\u003Aadd\u0028\u0029",
            "name": "add",
            "summary": "Registers\u0020a\u0020set\u0020of\u0020PSR\u002D0\u0020directories\u0020for\u0020a\u0020given\u0020prefix,\u0020either\nappending\u0020or\u0020prepending\u0020to\u0020the\u0020ones\u0020previously\u0020set\u0020for\u0020this\u0020prefix.",
            "url": "classes/Composer-Autoload-ClassLoader.html#method_add"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader\u003A\u003AaddPsr4\u0028\u0029",
            "name": "addPsr4",
            "summary": "Registers\u0020a\u0020set\u0020of\u0020PSR\u002D4\u0020directories\u0020for\u0020a\u0020given\u0020namespace,\u0020either\nappending\u0020or\u0020prepending\u0020to\u0020the\u0020ones\u0020previously\u0020set\u0020for\u0020this\u0020namespace.",
            "url": "classes/Composer-Autoload-ClassLoader.html#method_addPsr4"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader\u003A\u003Aset\u0028\u0029",
            "name": "set",
            "summary": "Registers\u0020a\u0020set\u0020of\u0020PSR\u002D0\u0020directories\u0020for\u0020a\u0020given\u0020prefix,\nreplacing\u0020any\u0020others\u0020previously\u0020set\u0020for\u0020this\u0020prefix.",
            "url": "classes/Composer-Autoload-ClassLoader.html#method_set"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader\u003A\u003AsetPsr4\u0028\u0029",
            "name": "setPsr4",
            "summary": "Registers\u0020a\u0020set\u0020of\u0020PSR\u002D4\u0020directories\u0020for\u0020a\u0020given\u0020namespace,\nreplacing\u0020any\u0020others\u0020previously\u0020set\u0020for\u0020this\u0020namespace.",
            "url": "classes/Composer-Autoload-ClassLoader.html#method_setPsr4"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader\u003A\u003AsetUseIncludePath\u0028\u0029",
            "name": "setUseIncludePath",
            "summary": "Turns\u0020on\u0020searching\u0020the\u0020include\u0020path\u0020for\u0020class\u0020files.",
            "url": "classes/Composer-Autoload-ClassLoader.html#method_setUseIncludePath"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader\u003A\u003AgetUseIncludePath\u0028\u0029",
            "name": "getUseIncludePath",
            "summary": "Can\u0020be\u0020used\u0020to\u0020check\u0020if\u0020the\u0020autoloader\u0020uses\u0020the\u0020include\u0020path\u0020to\u0020check\nfor\u0020classes.",
            "url": "classes/Composer-Autoload-ClassLoader.html#method_getUseIncludePath"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader\u003A\u003AsetClassMapAuthoritative\u0028\u0029",
            "name": "setClassMapAuthoritative",
            "summary": "Turns\u0020off\u0020searching\u0020the\u0020prefix\u0020and\u0020fallback\u0020directories\u0020for\u0020classes\nthat\u0020have\u0020not\u0020been\u0020registered\u0020with\u0020the\u0020class\u0020map.",
            "url": "classes/Composer-Autoload-ClassLoader.html#method_setClassMapAuthoritative"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader\u003A\u003AisClassMapAuthoritative\u0028\u0029",
            "name": "isClassMapAuthoritative",
            "summary": "Should\u0020class\u0020lookup\u0020fail\u0020if\u0020not\u0020found\u0020in\u0020the\u0020current\u0020class\u0020map\u003F",
            "url": "classes/Composer-Autoload-ClassLoader.html#method_isClassMapAuthoritative"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader\u003A\u003AsetApcuPrefix\u0028\u0029",
            "name": "setApcuPrefix",
            "summary": "APCu\u0020prefix\u0020to\u0020use\u0020to\u0020cache\u0020found\/not\u002Dfound\u0020classes,\u0020if\u0020the\u0020extension\u0020is\u0020enabled.",
            "url": "classes/Composer-Autoload-ClassLoader.html#method_setApcuPrefix"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader\u003A\u003AgetApcuPrefix\u0028\u0029",
            "name": "getApcuPrefix",
            "summary": "The\u0020APCu\u0020prefix\u0020in\u0020use,\u0020or\u0020null\u0020if\u0020APCu\u0020caching\u0020is\u0020not\u0020enabled.",
            "url": "classes/Composer-Autoload-ClassLoader.html#method_getApcuPrefix"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader\u003A\u003Aregister\u0028\u0029",
            "name": "register",
            "summary": "Registers\u0020this\u0020instance\u0020as\u0020an\u0020autoloader.",
            "url": "classes/Composer-Autoload-ClassLoader.html#method_register"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader\u003A\u003Aunregister\u0028\u0029",
            "name": "unregister",
            "summary": "Unregisters\u0020this\u0020instance\u0020as\u0020an\u0020autoloader.",
            "url": "classes/Composer-Autoload-ClassLoader.html#method_unregister"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader\u003A\u003AloadClass\u0028\u0029",
            "name": "loadClass",
            "summary": "Loads\u0020the\u0020given\u0020class\u0020or\u0020interface.",
            "url": "classes/Composer-Autoload-ClassLoader.html#method_loadClass"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader\u003A\u003AfindFile\u0028\u0029",
            "name": "findFile",
            "summary": "Finds\u0020the\u0020path\u0020to\u0020the\u0020file\u0020where\u0020the\u0020class\u0020is\u0020defined.",
            "url": "classes/Composer-Autoload-ClassLoader.html#method_findFile"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader\u003A\u003AgetRegisteredLoaders\u0028\u0029",
            "name": "getRegisteredLoaders",
            "summary": "Returns\u0020the\u0020currently\u0020registered\u0020loaders\u0020keyed\u0020by\u0020their\u0020corresponding\u0020vendor\u0020directories.",
            "url": "classes/Composer-Autoload-ClassLoader.html#method_getRegisteredLoaders"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader\u003A\u003AfindFileWithExtension\u0028\u0029",
            "name": "findFileWithExtension",
            "summary": "",
            "url": "classes/Composer-Autoload-ClassLoader.html#method_findFileWithExtension"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader\u003A\u003AinitializeIncludeClosure\u0028\u0029",
            "name": "initializeIncludeClosure",
            "summary": "",
            "url": "classes/Composer-Autoload-ClassLoader.html#method_initializeIncludeClosure"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader\u003A\u003A\u0024includeFile",
            "name": "includeFile",
            "summary": "",
            "url": "classes/Composer-Autoload-ClassLoader.html#property_includeFile"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader\u003A\u003A\u0024vendorDir",
            "name": "vendorDir",
            "summary": "",
            "url": "classes/Composer-Autoload-ClassLoader.html#property_vendorDir"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader\u003A\u003A\u0024prefixLengthsPsr4",
            "name": "prefixLengthsPsr4",
            "summary": "",
            "url": "classes/Composer-Autoload-ClassLoader.html#property_prefixLengthsPsr4"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader\u003A\u003A\u0024prefixDirsPsr4",
            "name": "prefixDirsPsr4",
            "summary": "",
            "url": "classes/Composer-Autoload-ClassLoader.html#property_prefixDirsPsr4"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader\u003A\u003A\u0024fallbackDirsPsr4",
            "name": "fallbackDirsPsr4",
            "summary": "",
            "url": "classes/Composer-Autoload-ClassLoader.html#property_fallbackDirsPsr4"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader\u003A\u003A\u0024prefixesPsr0",
            "name": "prefixesPsr0",
            "summary": "List\u0020of\u0020PSR\u002D0\u0020prefixes",
            "url": "classes/Composer-Autoload-ClassLoader.html#property_prefixesPsr0"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader\u003A\u003A\u0024fallbackDirsPsr0",
            "name": "fallbackDirsPsr0",
            "summary": "",
            "url": "classes/Composer-Autoload-ClassLoader.html#property_fallbackDirsPsr0"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader\u003A\u003A\u0024useIncludePath",
            "name": "useIncludePath",
            "summary": "",
            "url": "classes/Composer-Autoload-ClassLoader.html#property_useIncludePath"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader\u003A\u003A\u0024classMap",
            "name": "classMap",
            "summary": "",
            "url": "classes/Composer-Autoload-ClassLoader.html#property_classMap"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader\u003A\u003A\u0024classMapAuthoritative",
            "name": "classMapAuthoritative",
            "summary": "",
            "url": "classes/Composer-Autoload-ClassLoader.html#property_classMapAuthoritative"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader\u003A\u003A\u0024missingClasses",
            "name": "missingClasses",
            "summary": "",
            "url": "classes/Composer-Autoload-ClassLoader.html#property_missingClasses"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader\u003A\u003A\u0024apcuPrefix",
            "name": "apcuPrefix",
            "summary": "",
            "url": "classes/Composer-Autoload-ClassLoader.html#property_apcuPrefix"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader\u003A\u003A\u0024registeredLoaders",
            "name": "registeredLoaders",
            "summary": "",
            "url": "classes/Composer-Autoload-ClassLoader.html#property_registeredLoaders"
        },                {
            "fqsen": "\\Composer\\InstalledVersions",
            "name": "InstalledVersions",
            "summary": "This\u0020class\u0020is\u0020copied\u0020in\u0020every\u0020Composer\u0020installed\u0020project\u0020and\u0020available\u0020to\u0020all",
            "url": "classes/Composer-InstalledVersions.html"
        },                {
            "fqsen": "\\Composer\\InstalledVersions\u003A\u003AgetInstalledPackages\u0028\u0029",
            "name": "getInstalledPackages",
            "summary": "Returns\u0020a\u0020list\u0020of\u0020all\u0020package\u0020names\u0020which\u0020are\u0020present,\u0020either\u0020by\u0020being\u0020installed,\u0020replaced\u0020or\u0020provided",
            "url": "classes/Composer-InstalledVersions.html#method_getInstalledPackages"
        },                {
            "fqsen": "\\Composer\\InstalledVersions\u003A\u003AgetInstalledPackagesByType\u0028\u0029",
            "name": "getInstalledPackagesByType",
            "summary": "Returns\u0020a\u0020list\u0020of\u0020all\u0020package\u0020names\u0020with\u0020a\u0020specific\u0020type\u0020e.g.\u0020\u0027library\u0027",
            "url": "classes/Composer-InstalledVersions.html#method_getInstalledPackagesByType"
        },                {
            "fqsen": "\\Composer\\InstalledVersions\u003A\u003AisInstalled\u0028\u0029",
            "name": "isInstalled",
            "summary": "Checks\u0020whether\u0020the\u0020given\u0020package\u0020is\u0020installed",
            "url": "classes/Composer-InstalledVersions.html#method_isInstalled"
        },                {
            "fqsen": "\\Composer\\InstalledVersions\u003A\u003Asatisfies\u0028\u0029",
            "name": "satisfies",
            "summary": "Checks\u0020whether\u0020the\u0020given\u0020package\u0020satisfies\u0020a\u0020version\u0020constraint",
            "url": "classes/Composer-InstalledVersions.html#method_satisfies"
        },                {
            "fqsen": "\\Composer\\InstalledVersions\u003A\u003AgetVersionRanges\u0028\u0029",
            "name": "getVersionRanges",
            "summary": "Returns\u0020a\u0020version\u0020constraint\u0020representing\u0020all\u0020the\u0020range\u0028s\u0029\u0020which\u0020are\u0020installed\u0020for\u0020a\u0020given\u0020package",
            "url": "classes/Composer-InstalledVersions.html#method_getVersionRanges"
        },                {
            "fqsen": "\\Composer\\InstalledVersions\u003A\u003AgetVersion\u0028\u0029",
            "name": "getVersion",
            "summary": "",
            "url": "classes/Composer-InstalledVersions.html#method_getVersion"
        },                {
            "fqsen": "\\Composer\\InstalledVersions\u003A\u003AgetPrettyVersion\u0028\u0029",
            "name": "getPrettyVersion",
            "summary": "",
            "url": "classes/Composer-InstalledVersions.html#method_getPrettyVersion"
        },                {
            "fqsen": "\\Composer\\InstalledVersions\u003A\u003AgetReference\u0028\u0029",
            "name": "getReference",
            "summary": "",
            "url": "classes/Composer-InstalledVersions.html#method_getReference"
        },                {
            "fqsen": "\\Composer\\InstalledVersions\u003A\u003AgetInstallPath\u0028\u0029",
            "name": "getInstallPath",
            "summary": "",
            "url": "classes/Composer-InstalledVersions.html#method_getInstallPath"
        },                {
            "fqsen": "\\Composer\\InstalledVersions\u003A\u003AgetRootPackage\u0028\u0029",
            "name": "getRootPackage",
            "summary": "",
            "url": "classes/Composer-InstalledVersions.html#method_getRootPackage"
        },                {
            "fqsen": "\\Composer\\InstalledVersions\u003A\u003AgetRawData\u0028\u0029",
            "name": "getRawData",
            "summary": "Returns\u0020the\u0020raw\u0020installed.php\u0020data\u0020for\u0020custom\u0020implementations",
            "url": "classes/Composer-InstalledVersions.html#method_getRawData"
        },                {
            "fqsen": "\\Composer\\InstalledVersions\u003A\u003AgetAllRawData\u0028\u0029",
            "name": "getAllRawData",
            "summary": "Returns\u0020the\u0020raw\u0020data\u0020of\u0020all\u0020installed.php\u0020which\u0020are\u0020currently\u0020loaded\u0020for\u0020custom\u0020implementations",
            "url": "classes/Composer-InstalledVersions.html#method_getAllRawData"
        },                {
            "fqsen": "\\Composer\\InstalledVersions\u003A\u003Areload\u0028\u0029",
            "name": "reload",
            "summary": "Lets\u0020you\u0020reload\u0020the\u0020static\u0020array\u0020from\u0020another\u0020file",
            "url": "classes/Composer-InstalledVersions.html#method_reload"
        },                {
            "fqsen": "\\Composer\\InstalledVersions\u003A\u003AgetInstalled\u0028\u0029",
            "name": "getInstalled",
            "summary": "",
            "url": "classes/Composer-InstalledVersions.html#method_getInstalled"
        },                {
            "fqsen": "\\Composer\\InstalledVersions\u003A\u003A\u0024installed",
            "name": "installed",
            "summary": "",
            "url": "classes/Composer-InstalledVersions.html#property_installed"
        },                {
            "fqsen": "\\Composer\\InstalledVersions\u003A\u003A\u0024canGetVendors",
            "name": "canGetVendors",
            "summary": "",
            "url": "classes/Composer-InstalledVersions.html#property_canGetVendors"
        },                {
            "fqsen": "\\Composer\\InstalledVersions\u003A\u003A\u0024installedByVendor",
            "name": "installedByVendor",
            "summary": "",
            "url": "classes/Composer-InstalledVersions.html#property_installedByVendor"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\SajedZarinpour\\Spotplayer\\Controllers",
            "name": "Controllers",
            "summary": "",
            "url": "namespaces/sajedzarinpour-spotplayer-controllers.html"
        },                {
            "fqsen": "\\SajedZarinpour\\Spotplayer\\Facades",
            "name": "Facades",
            "summary": "",
            "url": "namespaces/sajedzarinpour-spotplayer-facades.html"
        },                {
            "fqsen": "\\SajedZarinpour\\Spotplayer\\Models",
            "name": "Models",
            "summary": "",
            "url": "namespaces/sajedzarinpour-spotplayer-models.html"
        },                {
            "fqsen": "\\SajedZarinpour\\Spotplayer\\Providers",
            "name": "Providers",
            "summary": "",
            "url": "namespaces/sajedzarinpour-spotplayer-providers.html"
        },                {
            "fqsen": "\\SajedZarinpour\\Spotplayer",
            "name": "Spotplayer",
            "summary": "",
            "url": "namespaces/sajedzarinpour-spotplayer.html"
        },                {
            "fqsen": "\\SajedZarinpour",
            "name": "SajedZarinpour",
            "summary": "",
            "url": "namespaces/sajedzarinpour.html"
        },                {
            "fqsen": "\\SajedZarinpour\\Spotplayer\\Traits",
            "name": "Traits",
            "summary": "",
            "url": "namespaces/sajedzarinpour-spotplayer-traits.html"
        },                {
            "fqsen": "\\Composer\\Autoload",
            "name": "Autoload",
            "summary": "",
            "url": "namespaces/composer-autoload.html"
        },                {
            "fqsen": "\\Composer",
            "name": "Composer",
            "summary": "",
            "url": "namespaces/composer.html"
        }            ]
);
